name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'osg-htc/')

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ref: main                      # Needed or it will checkout the wrong commit

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to OSG Harbor
      uses: docker/login-action@v1
      with:
        registry: hub.opensciencegrid.org
        username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
        password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.0
      with:
        context: .
        push: true
        tags: "hub.opensciencegrid.org/opensciencegrid/path-portal-documentation:latest"